# Generated by Django 3.2.5 on 2021-08-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
